---
name: "Publish Collection"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'galaxy.yml'

jobs:
  publish-collection:
    name: Publish Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
